# -*- coding: utf-8 -*-

"""
openweathermapapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from openweathermapapi.api_helper import APIHelper


class CurrentWeatherDataControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(CurrentWeatherDataControllerTests, cls).setUpClass()
        cls.controller = cls.client.current_weather_data
        cls.response_catcher = cls.controller.http_call_back

    # Get the current weather info
    def test_current_weather_data(self):
        # Parameters for the API call
        q = None

        # Perform the API call through the SDK function
        result = self.controller.current_weather_data(q)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


